services:
  kong:
    # image: kong/kong-gateway:latest
    build: ./kong
    container_name: kong
    mem_limit: 8192m
    cpus: 2.0
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      # - ONG_LICENSE_DATA
    depends_on:
      - kong-migration
      - kong-database
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    networks:
      - kong-net

  kong-migration:
    image: kong/kong-gateway:latest
    container_name: kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    depends_on:
      - kong-database
    command: ["kong", "migrations", "bootstrap"]
    networks:
      - kong-net

  kong-database:
    image: postgres:latest
    container_name: kong-database
    mem_limit: 1024m
    cpus: 1.0
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - 5432:5432
    networks:
      - kong-net

  api:
    build: ./api
    container_name: api-server
    mem_limit: 8192m
    cpus: 2.0
    ports:
      - "8888:8000"

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    mem_limit: 1024m
    cpus: 1.0
    ports:
      - "6379:6379"

networks:
  kong-net:
    name: kong-net
    driver: bridge
